# Generated by Django 6.0.4 on 2026-04-23 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('news', 'News'), ('education', 'Education'), ('makemoney', 'Makemoney'), ('digital', 'Digital'), ('technology', 'Technology')], default='technology', max_length=15),
        ),
    ]
