# Generated by Django 6.0.4 on 2026-04-23 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_post_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='earnings',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
